### PR TITLE
More explicit definition in what we mean for mentoring for software developers

### PR DESCRIPTION
**Pull request by srbd**
## What does this change?
Includes mentoring and what would and wouldn't count for mentoring criteria in level 2.

### CODE REVIEW

**Review by davidfurey — APPROVED** [review]
Looks good to me.  Is there an alternative wording of `in a non-judgemental way` that is framed as a positive rather than a negative?  Maybe supportive or encouraging?

**Comment by srbd** [comment]
> Looks good to me. Is there an alternative wording of `in a non-judgemental way` that is framed as a positive rather than a negative? Maybe supportive or encouraging?

I like both!

**Comment by akash1810** [comment]
Should "Each quarter" be rephrased to "Regularly" for further clarity?

**Comment by davidfurey** [comment]
> Should "Each quarter" be rephrased to "Regularly" for further clarity?

Do you intend "Regularly" be be more or less frequently than each quarter?

**Comment by akash1810** [comment]
> > Should "Each quarter" be rephrased to "Regularly" for further clarity?
> 
> Do you intend "Regularly" be be more or less frequently than each quarter?

More frequently. I read "each quarter" as once every ~90 days...

**Review by akash1810 — APPROVED** [review]

**Review by mchv — APPROVED** [review]

**Pull request merged**
